### ISSUE TITLE
U balance incorrect (showing 0) 

### ISSUE THREAD

**Issue by tzarebczan** [th8ta/ArConnect#128]
I have some U, but the ARconnect wallet shows 0. Is this a known bug? 

You can see Bazaar picks it up: 

![image](https://github.com/arconnectio/ArConnect/assets/8120721/c2b1c9bf-64c9-4cf2-a8dd-8876f3a86675)
![image](https://github.com/arconnectio/ArConnect/assets/8120721/2c57176b-2c4a-44cb-9716-67b21ce1aad0)

**Comment by martonlederer** [comment]
Unfortunately different Warp DRE nodes have different token states cached. If you try to switch to an another one (that has $U) and wait a little bit on the main screen, you'll see the balances update. 
We're going to be implementing a solution for this shortly.

**Comment by tzarebczan** [comment]
Thanks, that made it show the balance. I then tried to send some U, and it gives me a success + this tx:https://viewblock.io/arweave/tx/DZ4LH5Udq4pAaban8gXhJEDBlCuvXL-bTA_ggsHZ6XA But the recipient doesn't see any U, and my balance didn't go down. 

Trying another now... https://viewblock.io/arweave/tx/6L-AzvLM3FJdpn2bfKFkp2uKxLRG13hdhUoAFVbYWDI
