### ISSUE TITLE
U transfers don't work?

### ISSUE THREAD

**Issue by tzarebczan** [th8ta/ArConnect#133]
Originally mentioned here, but will start a new issue: https://github.com/arconnectio/ArConnect/issues/128#issuecomment-1746816556

Neither my first or 2nd transaction resulted in a successful U transfer, but the UI gives confirmation of success and a tx.  My balance does not decrease, and the recipient's does not increase. 

1st tx:  https://viewblock.io/arweave/tx/DZ4LH5Udq4pAaban8gXhJEDBlCuvXL-bTA_ggsHZ6XA 

2nd tx:  https://viewblock.io/arweave/tx/6L-AzvLM3FJdpn2bfKFkp2uKxLRG13hdhUoAFVbYWDI

**Comment by tzarebczan** [comment]
With the latest version, I now get a "transaction sent" message, but no transaction details and it doesn't look like a tx is generated.

**Comment by tzarebczan** [comment]
Any updates on this?

**Comment by nicholaswma** [comment]
@tzarebczan hey sorry for the delayed response! this fix is rolling out on the next release

**Comment by tzarebczan** [comment]
Thank you! I also tried to go to AR://getu recently and transfers fail there...I thought this was all related ,but maybe not. It seems to want to use dre-6 to make the API call, which doesn't have the contract. I've let some of the other folks know about this issue too, not sure who controls what DRE is selected.

**Comment by MattSoloing** [comment]
@tzarebczan This should be fixed now with version 1.0.10 - https://github.com/arconnectio/ArConnect/releases/tag/1.0.10
