### ISSUE TITLE
tokens balance doesn't show if AR balance 0

### ISSUE THREAD

**Issue by tzarebczan** [th8ta/ArConnect#137]
![image](https://github.com/arconnectio/ArConnect/assets/8120721/d3795dd7-a850-47b3-9f43-0903df29f3dc)

I have some U and STAMP, but it won't show those tokens:
![image](https://github.com/arconnectio/ArConnect/assets/8120721/89d6758b-2586-486c-b80e-2714a6c2cc40)

**Comment by MattSoloing** [comment]
This should be fixed in v1.6.1

https://github.com/arconnectio/ArConnect/releases/tag/v1.6.1
