### ISSUE TITLE
Clicking the ArConnect extension icon in Chrome doesn't work

### ISSUE THREAD

**Issue by garyrob** [th8ta/ArConnect#27]
I pinned the ArConnect extension in the Chrome extensions manager, so that its icon is visible on the browser UI. When I click the icon,  I see what appears to be the bottom of an extension's window near the top of Chrome, but only a small portion of such a window, with no content at all.

**Comment by martonlederer** [comment]
This is a very strange issue, that as of now, I couldn't reproduce. I'll investigate this ASAP. Until then, try reloading or reinstalling the extension.

**Comment by jim-toth** [comment]
Hey! So this happened to me as well.  Opening dev tools for me uncovered an error where the network I was connected to doesn't have a `/balance` endpoint, so there's an undefined error somewhere.  I'll try to get a log of it.

I was using `arlocal` and changed my settings in ArConnect to `http://localhost:1984`.  As of right now `arlocal` doesn't provide a `/balance` endpoint which seems to crash the ArConnect extension UI.

Hope this helps!

**Comment by jim-toth** [comment]
`U.fiatBalance` is `null` when `toLocaleString` is called, because `arlocal` doesn't provide a `/balance` endpoint I assume

```
Uncaught (in promise) TypeError: Cannot read property 'toLocaleString' of null
    at rd (popup.js:977)
    at JR (popup.js:24)
    at DZ (popup.js:28)
    at PZ (popup.js:28)
    at kRe (popup.js:28)
    at n4 (popup.js:28)
    at yN (popup.js:26)
    at popup.js:24
    at Un.unstable_runWithPriority (popup.js:20)
    at Cv (popup.js:24)
```

**Comment by martonlederer** [comment]
Hey, this will definitely help. @garyrob can you maybe share your logs too?

**Comment by jim-toth** [comment]
After a little digging I assume it's this line:

https://github.com/th8ta/ArConnect/blob/development/src/views/Popup/routes/Home.tsx#L276

**Comment by jim-toth** [comment]
@martonlederer Any way to cleanly reset the extension without straight up reinstalling?

**Comment by martonlederer** [comment]
I'm afraid no :/

**Comment by martonlederer** [comment]
If any of you could build the `development` branch and test if the fix worked, that would help a lot

**Comment by jim-toth** [comment]
@martonlederer yep, built and installed the extension locally, connected to `arlocal` on `http://localhost:1984` and no more issue 😄
