### ISSUE TITLE
Duplicate description

### ISSUE THREAD

**Issue by pChao3** [th8ta/ArConnect#349]
Hi, I noticed that in the wallet connection api, the description of these two fields is the same, the description of ACCESS_ALL_ADDRESSES should be wrong, right?       
   
ACCESS_PUBLIC_KEY | **Enable the app to access the active wallet's public key**
ACCESS_ALL_ADDRESSES | **Enable the app to access the active wallet's public key**

**Comment by 7i7o** [comment]
Thank you for noticing this!
We fixed this in the docs 👍
