### ISSUE TITLE
Signing with ArConnect 'signDataItem' is slow

### ISSUE THREAD

**Issue by ppedziwiatr** [th8ta/ArConnect#413]
signing dataItem with ArConnect seems to take 200-300ms (sometimes even more - 500ms or even over a second!). 
The same using the native sign in arbundles library takes 10-12ms...

Is there a chance for optimizing this? Do you know what might the reason for such a big difference? Unfortunatelly this is killing our app (where we need almost real-time processing)

Code for signing with ArConnect:
```
const now = Date.now();
  const signedDataItem = await window.arweaveWallet.signDataItem(dataItem);
  console.log(`Signing with ArConnect ${Date.now() - now}ms`);
```

Code for signing with arbundles lib:
```
const dataItem = createData('1234', signer, {
    tags: window.warpAO.messageTags(moduleId, processId, message),
    target: processId,
  });
await dataItem.sign(signer);
```
```
ArConnect version:
v1.14.3

chrome-mv3
```

**Comment by nicholaswma** [comment]
Closed by [429](https://github.com/arconnectio/ArConnect/pull/429)
