### ISSUE TITLE
What format does ArConnect expect logo to be?

### ISSUE THREAD

**Issue by KeeJef** [th8ta/ArConnect#69]
The docs seem to indicate that I can display an image alongside my app name when requesting the user connect to ArConnect, it seems to indicate that it expects a string, but how should i encode my image inside a string? the docs is not clear about this, B64 encode? or something else?

```
{
  name?: string; // optional application name
  logo?: string; // optional application logo
}
```

Might want to make a note in the docs too

**Comment by martonlederer** [comment]
Hey sorry for the delay here 😅, hope you figured it out, but for future reference, the logo should be the same format, as what you would use for an html `img`tag. So you can submit an URL or a b64 encoded image string as well.
