### ISSUE TITLE
@Types/Arconnect doesn't include type definition for DISPATCH

### ISSUE THREAD

**Issue by DanMacDonald** [th8ta/ArConnect#71]
https://www.npmjs.com/package/@types/arconnect

is missing the `DISPATCH` permission type causing strict type checkers to 🤮 

![image](https://user-images.githubusercontent.com/3269261/166076104-f34ed32a-6319-448d-a6af-55e848ceabe9.png)

**Comment by martonlederer** [comment]
Hey, I'll push an update today!

**Comment by martonlederer** [comment]
I just checked. You are not using the correct package, you should be using https://npmjs.org/arconnect

**Comment by DanMacDonald** [comment]
I don't include the package at all..  `arweave-js` does as a dependency. It seems to be including an older version...

https://github.com/ArweaveTeam/arweave-js/blob/master/package.json#L90

**Comment by martonlederer** [comment]
Still, as I said, you should follow the instructions in the docs and it will fix the errors. Could you please try that first?

**Comment by DanMacDonald** [comment]
I don't have the problem personally, it was reported by a user on the arweave dev discord and I investigated. They also worked around the issue eventually.  My thinking was that it might be nice to improve the developer experience.  Perhaps by making a PR to arweave-js?

**Comment by martonlederer** [comment]
I agree developer experience is important. However because this is not an ArConnect issue, it might be better to open an issue in the arweave-js repo instead

**Comment by DanMacDonald** [comment]
That I can do!

**Comment by martonlederer** [comment]
Thank you very much!!
